---
- name: Copy NGINX server_files
  copy:
    src: "nginx/"
    dest: "/home/{{ user_name }}/nginx"
    mode: "0755"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"

- name: Start NGINX container
  command: "{{ docker_compose_path }} -f /home/{{ user_name }}/nginx/docker-compose.yml up -d"
  become: yes
  become_user: "{{ user_name }}"
  ignore_errors: true

